# refer to https://docs.litellm.ai/docs/providers/

passthrough_mini_db = {
    "gpt-4o": {
        "backend": "litellm",
        "provider": "openai",
        "tokenizer_path": "Xenova/gpt-4o",
        "resolve_as": "gpt-4o",
        "T": 128_000,
        "T_out": 4096,
        "filter_caps": ["chat", "tools"],
    },
    "gpt-4-turbo": {
        "backend": "litellm",
        "provider": "openai",
        "tokenizer_path": "Xenova/gpt-4",
        "resolve_as": "gpt-4-turbo",
        "T": 128_000,
        "T_out": 4096,
        "filter_caps": ["chat", "tools"],
    },
    "gpt-4": {
        "backend": "litellm",
        "provider": "openai",
        "tokenizer_path": "Xenova/gpt-4",
        "resolve_as": "gpt-4-0125-preview",
        "T": 128_000,
        "T_out": 4096,
        "filter_caps": ["chat", "tools"],
    },
    "gpt-3.5-turbo": {
        "backend": "litellm",
        "provider": "openai",
        "tokenizer_path": "Xenova/gpt-3.5-turbo-16k",
        "resolve_as": "gpt-3.5-turbo-1106",
        "T": 16_000,
        "T_out": 4096,
        "filter_caps": ["chat", "tools"],
    },
    "claude-3-5-sonnet": {
        "backend": "litellm",
        "provider": "anthropic",
        "tokenizer_path": "Xenova/claude-tokenizer",
        "resolve_as": "claude-3-5-sonnet-20240620",
        "T": 200_000,
        "T_out": 4096,
        "filter_caps": ["chat", "tools"],
    },
    "claude-3-haiku": {
        "backend": "litellm",
        "provider": "anthropic",
        "tokenizer_path": "Xenova/claude-tokenizer",
        "resolve_as": "claude-3-haiku-20240307",
        "T": 200_000,
        "T_out": 4096,
        "filter_caps": ["chat", "tools"],
    },
    "claude-3-opus": {
        "backend": "litellm",
        "provider": "anthropic",
        "tokenizer_path": "Xenova/claude-tokenizer",
        "resolve_as": "claude-3-opus-20240229",
        "T": 200_000,
        "T_out": 4096,
        "filter_caps": ["chat", "tools"],
    },
    "claude-3-sonnet": {
        "backend": "litellm",
        "provider": "anthropic",
        "tokenizer_path": "Xenova/claude-tokenizer",
        "resolve_as": "claude-3-sonnet-20240229",
        "T": 200_000,
        "T_out": 4096,
        "filter_caps": ["chat", "tools"],
    },
    "claude-2.1": {
        "backend": "litellm",
        "provider": "anthropic",
        "tokenizer_path": "Xenova/claude-tokenizer",
        "resolve_as": "claude-2.1",
        "T": 100_000,
        "T_out": 4096,
        "filter_caps": ["chat"],
    },
    "claude-instant-1.2": {
        "backend": "litellm",
        "provider": "anthropic",
        "tokenizer_path": "Xenova/claude-tokenizer",
        "resolve_as": "claude-instant-1.2",
        "T": 100_000,
        "T_out": 4096,
        "filter_caps": ["chat"],
    },
}
