import { Usage } from "../../services/refact";

// TODO: update this with actual message
export const USAGE_COUNTER_STUB_GPT: Usage = {
  coins: 0,
  tokens_prompt: 3391,
  tokens_cache_read: 3328,
  tokens_completion: 30,
  pp1000t_prompt: 0,
  pp1000t_cache_read: 0,
  pp1000t_completion: 0,
  tokens_prompt_text: 0,
  tokens_prompt_audio: 0,
  tokens_prompt_image: 0,
  tokens_prompt_cached: 0,
  tokens_cache_creation: 0,
  pp1000t_cache_creation: 0,
  tokens_completion_text: 0,
  tokens_completion_audio: 0,
  tokens_completion_reasoning: 0,
  pp1000t_completion_reasoning: 0,
};

export const USAGE_COUNTER_STUB_ANTHROPIC: Usage = {
  coins: 0,
  tokens_completion: 142,
  tokens_prompt: 5,
  tokens_cache_creation: 3291,
  tokens_cache_read: 3608,
  pp1000t_prompt: 0,
  pp1000t_cache_read: 0,
  pp1000t_completion: 0,
  tokens_prompt_text: 0,
  tokens_prompt_audio: 0,
  tokens_prompt_image: 0,
  tokens_prompt_cached: 0,
  pp1000t_cache_creation: 0,
  tokens_completion_text: 0,
  tokens_completion_audio: 0,
  tokens_completion_reasoning: 0,
  pp1000t_completion_reasoning: 0,
};

export const USAGE_COUNTER_STUB_INLINE: Usage = {
  coins: 0,
  tokens_prompt: 3391,
  tokens_completion: 142,
  tokens_cache_read: 0,
  pp1000t_prompt: 0,
  pp1000t_cache_read: 0,
  pp1000t_completion: 0,
  tokens_prompt_text: 0,
  tokens_prompt_audio: 0,
  tokens_prompt_image: 0,
  tokens_prompt_cached: 0,
  tokens_cache_creation: 0,
  pp1000t_cache_creation: 0,
  tokens_completion_text: 0,
  tokens_completion_audio: 0,
  tokens_completion_reasoning: 0,
  pp1000t_completion_reasoning: 0,
};
