select_and_refactor = {
    "function_name": "select-and-refactor",
    "label": "Select & Refactor",
    "supports_highlight": 0,
    "supports_selection": 1,
    "selected_lines_min": 1,
    "selected_lines_max": 20,
    "supports_languages": "*.*",
    "mini_html": "<div>\n    <p>Default action for any typed intent, if some code is selected.</p>\n    <br/>\n    <img src=\"https://staging.smallcloud.ai/gif/select-and-refactor-01.gif\" alt=\"\" style=\"max-width: 100%\" loop>\n    <br/>\n    <p>Works best for:</p>\n    <ul>\n        <li>Local refactoring, such as \"replace with list comprehension\", \"use lambda\"</li>\n        <li>Simple instructions, such as \"Replace ul with ol\"</li>\n        <li>Convert dict to class</li>\n        <li>Fixing types, syntax, writing docstrings</li>\n    </ul>\n    <p>Don't forget to run tests after any refactoring.</p>\n</div>\n\n",
    "model": "CONTRASTcode",
    "model_fixed_intent": "",
    "function_selection": "diff-selection",
    "function_hl_click": "",
    "function_highlight": "",
    "catch_all_selection": 1,
    "catch_all_hl": 0,
}

hl_and_fix = {
    "function_name": "hl-and-fix",
    "label": "Highlight & Fix",
    "supports_highlight": 1,
    "supports_selection": 0,
    "selected_lines_min": 0,
    "selected_lines_max": 0,
    "supports_languages": "*.*",
    "mini_html": "<div>\n    <p>Default action for any typed intent, if no code is selected.</p>\n    <br/>\n    <p>This tool highlights all the places that is likely to change given your intent.</p>\n    <br/>\n    <p>Click on the highlighted area, the model will try to generate a change in code according to your intent.</p>\n    <br/>\n    <img src=\"https://staging.smallcloud.ai/gif/highlight-and-refactor-03.gif\" alt=\"\" style=\"max-width: 100%\" loop>\n    <br/>\n    <p>Works best for:</p>\n    <ul>\n        <li>Fixing types, variables, syntax</li>\n        <li>Simple refactoring</li>\n    </ul>\n</div>\n",
    "model": "CONTRASTcode",
    "model_fixed_intent": "",
    "function_selection": "",
    "function_hl_click": "diff-atcursor",
    "function_highlight": "highlight",
    "catch_all_selection": 0,
    "catch_all_hl": 1}
