from refact_scratchpads.scratchpad import ScratchpadBase
from refact_scratchpads.scratchpad_completion import ScratchpadCompletion
from refact_scratchpads.scratchpad_2022q4_diff import ScratchpadDiff

from refact_scratchpads.scratchpad_hf import ScratchpadHuggingfaceBase
from refact_scratchpads.scratchpad_hf import ScratchpadHuggingfaceCompletion
from refact_scratchpads.scratchpad_hf import ScratchpadFIM
from refact_scratchpads.scratchpad_hf import ScratchpadFIM_SuffixFirst
from refact_scratchpads.scratchpad_hf import ScratchpadCodeLlama
from refact_scratchpads.scratchpad_hf import ScratchpadHuggingfaceStarChat
from refact_scratchpads.scratchpad_hf import ScratchpadHuggingfaceWizard
from refact_scratchpads.scratchpad_hf import ScratchpadHuggingfaceLlama2
from refact_scratchpads.scratchpad_hf import ScratchpadHuggingfaceRefact
