from refact_scratchpads.scratchpad import ScratchpadBase
from refact_scratchpads.scratchpad_completion import ScratchpadCompletion
from refact_scratchpads.scratchpad_2022q4_diff import ScratchpadDiff
from refact_scratchpads.scratchpad_bigcode import ScratchpadBigCode
from refact_scratchpads.scratchpad_bigchat import ScratchpadBigChat
from refact_scratchpads.scratchpad_starchat import ScratchpadStarChat
from refact_scratchpads.scratchpad_refact import ScratchpadRefact

from refact_scratchpads.scratchpad_hf import ScratchpadHuggingface

from refact_scratchpads.scratchpad_hf import ScratchpadHuggingfaceStarChat
from refact_scratchpads.scratchpad_hf import ScratchpadHuggingfaceWizard
from refact_scratchpads.scratchpad_hf import ScratchpadHuggingfaceWizardVicuna
