FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    git \
    libssl-dev \
    pkg-config \
    protobuf-compiler \
    && rm -rf /var/lib/apt/lists/*

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH=/root/.cargo/bin:$PATH

WORKDIR /refact-lsp

COPY Cargo.toml build.rs ./

RUN mkdir src && echo 'fn main() { println!("Dummy main to satisfy Cargo"); }' > src/main.rs

RUN cargo fetch
RUN cargo check

RUN rm -rf src

COPY . .

RUN cargo build

RUN mkdir -p /output && cp target/debug/refact-lsp /output/

