import { Flex, Text, useThemeContext } from "@radix-ui/themes";
import { TourBox } from "./TourBox";
import { TourTitle } from "./TourTitle";
import { TourButton } from "./TourButton";
import { useAppDispatch } from "../../hooks";
import { finish } from "../../features/Tour";

export const TourEnd = () => {
  const appearance = useThemeContext().appearance;

  const dispatch = useAppDispatch();
  const onPressNext = () => {
    dispatch(finish());
  };

  return (
    <Flex direction="column" gap="2" maxWidth="540px" m="8px">
      <TourBox style={{ gap: "15px", alignSelf: "center" }}>
        <TourTitle title="Your Refact product tour is finished!" />
        <Text
          style={{
            color: appearance == "dark" ? "black" : "white",
          }}
        >
          {
            'The workflow to learn first: select a few lines in your code, hit F1, ask model to change it. When you are happy with the result, paste it back into the editor using the "Diff" button. You will see a diff between your selection and the code generated by the model, so it\'s easy to confirm if those are the changes you want.'
          }
        </Text>
        <TourButton title="Ready to use" onClick={onPressNext} />
      </TourBox>
    </Flex>
  );
};
