from code_contrast.scratchpad.scratchpad import ScratchpadBase
from code_contrast.scratchpad.scratchpad_completion import ScratchpadCompletion
from code_contrast.scratchpad.scratchpad_2022q4_diff import ScratchpadDiff
from code_contrast.scratchpad.scratchpad_bigcode import ScratchpadBigCode
from code_contrast.scratchpad.scratchpad_bigchat import ScratchpadBigChat
from code_contrast.scratchpad.scratchpad_starchat import ScratchpadStarChat
