name: Refact Agent GUI CI build and Publish (Node.js)

on:
  workflow_dispatch:
    inputs:
      perform_publish:
        required: true
        type: boolean
        default: false
        description: Publish to NPM Registry after successful build
  # Automatic trigger for alpha and dev branches
  push:
    branches: [main, dev]
    paths:
      - 'refact-agent/gui/**'
      - '.github/workflows/agent_gui_*'
  pull_request:
    paths:
      - 'refact-agent/gui/**'
      - '.github/workflows/agent_gui_*'

defaults:
  run:
    working-directory: refact-agent/gui

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*, latest]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: refact-agent/gui/package-lock.json

      # Disable Husky install during npm ci
      - name: Install dependencies
        run: |
          npm pkg delete scripts.prepare
          npm ci

      - run: npm run test
      - run: npm run format:check
      - run: npm run types
      - run: npm run lint
      - run: npm run build

      - run: |
          name=$(echo -n "${{ matrix.node-version }}" | tr -cd '[[:alnum:]]')
          echo "ARTIFACT_NAME=$name" >> $GITHUB_ENV

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: refact-chat-js-${{ env.ARTIFACT_NAME }}
          if-no-files-found: ignore
          path: refact-agent/gui/dist

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: inputs.perform_publish || (github.ref == 'refs/heads/dev' && github.event_name == 'push')

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          npm pkg delete scripts.prepare
          npm ci

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - run: npm run build

      - name: Bump version
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            npm run alpha:version
          else
            npm version patch -m "Bump version to %s [skip ci]"
          fi

      - name: Publish to NPM Registry
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev"]]; then
            npm run alpha:publish
          else
            npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push tag and version bump commit
        run: |
          git push
          git push --tags
