name: Refact Agent GUI CI build (Node.js)

on:
  push:
    branches: [main, dev]
    paths: 
      - "refact-agent/gui/**"
      - ".github/workflows/agent_gui_*"
  pull_request:
    paths:
      - "refact-agent/gui/**"
      - ".github/workflows/agent_gui_*"

defaults:
  run:
    working-directory: refact-agent/gui

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*, latest]

    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: refact-agent/gui/package-lock.json

      # Disable Husky install during npm ci
      - name: Install dependencies
        run: |
          npm pkg delete scripts.prepare
          npm ci

      - run: npm run test
      - run: npm run format:check
      - run: npm run types
      - run: npm run lint
      - run: npm run build
      - run: npm pack

      - run: |
          name=$(echo -n "${{ matrix.node-version }}" | tr -cd '[[:alnum:]]')
          pkg_name=$(ls refact-chat-js-*.tgz)
          echo "ARTIFACT_NAME=$name" >> $GITHUB_ENV
          echo "PACKAGE_NAME=$pkg_name" >> $GITHUB_ENV
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}-${{ env.PACKAGE_NAME }}
          if-no-files-found: ignore
          path: refact-agent/gui/${{env.PACKAGE_NAME}}
          compression-level: 0