name: Build base
on:
  workflow_dispatch:

jobs:
  build_base:
    name: Build base
    runs-on: ubuntu-latest
    steps:
      # Free GitHub Actions Environment Disk Space
      - name: Maximize Build Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: false
          context: .
          file: .github/cicl/Dockerfile_base
          tags: smallcloud/refact_base:latest
          platforms: |
            linux/amd64
