name: Refact Docs Build
# This workflow can be triggered manually
on:
  workflow_dispatch:

jobs:
  setup-vars:
    name: Setup variables
    runs-on: ubuntu-latest
    outputs:
      now_tag: ${{ steps.set-variables.outputs.now_tag }}
    steps:
      - id: set-variables
        name: Setup variables
        shell: bash
        run: |
          GIT_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          if [[ ${GIT_BRANCH} == "main" ]]; then 
              echo "now_tag=${GIT_BRANCH}.$(TZ=UTC date +'%Y-%m-%dT%H-%M-%SZ')" >> "$GITHUB_OUTPUT"
          else
              echo "now_tag=${GIT_BRANCH}" >> "$GITHUB_OUTPUT"
          fi

  build-and-push-image:
    name: Dockerize and push
    runs-on: ubuntu-latest
    needs: [setup-vars]
    steps:
      # Free GitHub Actions Environment Disk Space
      - name: Maximize Build Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc

      - uses: actions/checkout@v3
      - name: npm install
        working-directory: ./docs
        run: |
          npm install
          npm run build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Install GCloud
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: europe-west4-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./docs
          file: ./docs/Dockerfile
          push: true
          tags: |
            europe-west4-docker.pkg.dev/small-storage1/databases-and-such/docs-refact-ai:${{ needs.setup-vars.outputs.now_tag }}
          platforms: |
            linux/amd64
